from __future__ import annotations

from os import PathLike
from typing import Iterable, MutableMapping, Protocol, Any

class KeyStore(Protocol):
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...

    def keys(self) -> Iterable[str]: ...
    def items(self): ...
