### Parameters for Blastn search
num_threads: 1 #number of threads for parallel run of blast
word_size: 10 #word size for the blastn seed (exact match to target)
coverage: 50 #minimum coverage between probes and target sequence, ranging from 0 to 100% (full coverage)
percent_identity: 80 #maximum similarity between probes and target sequences, ranging from 0 to 100% (no missmatch)
ligation_site: 0 #coverage between probes and target sequence should not span ligation site (e.g. ligation_site = 5 would correspond to -4 to +5 nt around probe center), if ligation_site = 0, omit this requirement

# How many Blast runs should run in parallele
number_batchs: 10 #number of threads running in parallel, each starts one blastn run
number_subbatches: 1 #number of batches into which the input is divided, i.e. divide list of probes into 50 batches to reduce required memory for loading blast results
