### General parameters
n_jobs: 2 # number of cores used to run the pipeline
dir_output: output # name of the directory where the output files will be written
file_format: tsv # fromat of the written files, can be "tsv" or "gtf"
min_oligos_per_gene: 0 # minimum number of oligos that a gene must have before it gets deleted
write_removed_genes: True # write in a file the removed genes
write_intermediate_steps: True # writes the oligo sequences after each step of the pipeline


### Parameters for genome and gene annotation
source: ncbi # define annotation source
species: human # currently supported species: human or mouse
annotation_release: current # release number (e.g. 109 or 109.20211119 for ncbi) of annotation or 'current' to use most recent annotation release. Check out release numbers for NCBI at ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/


### Parameters for oligo sequences generation
file_genes: ./data/genes/ncbi_10.txt # file with a list the genes used to generate the oligos sequences, set as None if al the genes are used
oligo_length_min: 38 #min length of oligos
oligo_length_max: 45 #max length of oligos
block_size: 50


### Parameters for the property filers
# oligo sequence
GC_content_min: 40 #minimum GC content of oligos
GC_content_max: 60 #maximum GC content of oligos
Tm_min: 52 #55 #minimum melting temperature of oligos
Tm_max: 67 #63 #maximum melting temperature of oligos
# padlock arms
min_arm_length: 10 #min length of each arm
max_arm_Tm_dif: 2 #maximum melting temperature difference of both arms
arm_Tm_min: 38 #41 #minimum melting temperature of each arm (difference shouldn't be higher than 5! But range is not super important, the lower the better)
arm_Tm_max: 49 #46 #maximum melting temperature of each arm


### Parameters for the specificity filters
# Bowtie Ligation Region filter
ligation_region_size: 5 #coverage between oligos and target sequence should not span region around ligation site (e.g. ligation_region = 5 would correspond to -4 to +5 nt around ligation site), if ligation_region = 0, omit this requirement
# Blastn Similarity Filter
word_size: 10 #word size for the blastn seed (exact match to target)
coverage: 50 #minimum coverage between oligos and target sequence, ranging from 0 to 100% (full coverage)
percent_identity: 80 #maximum similarity between oligos and target sequences, ranging from 0 to 100% (no missmatch)


### Parameters for the oligo efficiency
# Here also Tm_min, Tm_max, GC_content_min, GC_content_max are used, but have been defined before
Tm_opt: 60 #60 #optimal melting temperature of oligos
GC_content_opt: 50 #optimal GC content of oligos
Tm_weight: 1 # weight of the Tm of the oligo in the efficiency score
GC_weight: 1 # weight of the GC content of the oligo in the efficiency score


### Parameters for the oligosets generation
oligoset_size: 5 #ideal number of oligos per oligoset
min_oligoset_size: 2 #minimum number of oligos per oligoset
n_sets: 100 # maximum number of sets per gene


### Parameters for the padlock detection oligo design
detect_oligo_length_min: 18 # min length of detection oligo
detect_oligo_length_max: 25 # max length of detection oligo
detect_oligo_Tm_opt: 32 # optimal melting temperature of detection oligo


### Parameters for Melting Temperature 
# The melting temperature is used in 2 different stages (property filters and padlock detection oligo design), where a few parameters are shared and the others differ.
# parameters for melting temperature -> for more information on parameters, see: https://biopython.org/docs/1.75/api/Bio.SeqUtils.MeltingTemp.html#Bio.SeqUtils.MeltingTemp.Tm_NN
Tm_parameters:
    shared:
        check: True
        strict: True
        c_seq: null
        shift: 0
        nn_table: DNA_NN3
        tmm_table: DNA_TMM1
        imm_table: DNA_IMM1
        de_table: DNA_DE1
        dnac1: 50 #[nM]
        dnac2: 0
        selfcomp: False
        dNTPs: 0
        saltcorr: 7
    property_filter:
        Na: 1.25 #[mM]
        K: 75 #[mM]
        Tris: 20 #[mM]
        Mg: 10 #[mM]
    detection_oligo:
        Na: 39 #[mM]
        K: 0 #[mM]
        Tris: 0 #[mM]
        Mg: 0 #[mM]

Tm_correction_parameters:
    shared:
        DMSO: 0
        DMSOfactor: 0.75
        fmdfactor: 0.65
        fmdmethod: 1
        GC: null
    property_filter:
        fmd: 20
    detection_oligo:
        fmd: 30
