# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

# Add parent dir to known paths
sys.path.insert(0, os.path.abspath("../../"))


# -- Project information -----------------------------------------------------

project = "Oligo Designer Toolsuite"
copyright = "Helmholtz AI 2024"
author = "Lisa Barros de Andrade e Sousa, Isra Mekki, Franceso Campi"

# The full version, including alpha/beta/rc tags
release = "0.1"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.mathjax",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "nbsphinx",
    "nbsphinx_link",
    "myst_parser",
]
autosummary_generate = True  # Turn on sphinx.ext.autosummary
add_module_names = False

# Add any paths that contain templates here, relative to this directory.
# templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "renku"
html_logo = "_static/ODT_logo.png"

html_title = "Oligo Designer Toolsuite"
html_theme_options = {"logo_only": True}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = []


# -- Extension configuration -------------------------------------------------

autodoc_member_order = "bysource"

nbsphinx_thumbnails = {
    "_getting_started/_tutorials/1-oligo-sequences-generation": "_static/tutorials/1-oligo-sequences-generation.png",
    "_getting_started/_tutorials/2-oligo-database": "_static/tutorials/2-oligo-database.png",
    "_getting_started/_tutorials/3-property-filters": "_static/tutorials/3-property-filters.png",
    "_getting_started/_tutorials/4-specificity-filters": "_static/tutorials/4-specificity-filters.png",
    "_getting_started/_tutorials/5-oligoset-generation": "_static/tutorials/5-oligoset-generation.png",
}
