### Parameters for genome and gene annotation
# Which annotation should be used? Ensemble or NCBI?
source: ncbi # available sources: 'ncbi' and 'ensemble'

# If own annotation files should be used, provide a gene annotation (gtf) and genome file (fasta), e.g. file_gene_gtf: ./data/Homo_sapiens.GRCh38.104.gtf
# If no files are provided (e.g. file_gene_gtf: null), gene annotation file (gtf) as well as genome file (fasta) are retrieved from 'source'.
file_gene_gtf: null  # ./data_ncbi/annotations/GCF_000001405.39_GRCh38.p13_genomic.gtf
file_genome_fasta: null  # ./data_ncbi/annotations/GCF_000001405.39_GRCh38.p13_genomic.fna



### Which geneset should be used?
# If probes should be designed for all genes of the provided annotation, leave gene_list empty, i.e. gene_list: null
# If probes should only be designed for specific genes, provide a file with a list of genes (each row should contain one gene name in ensemble or NCBI format), e.g. gene_list: ./data/ensemble_gene_list.txt
file_genes: ${hydra:runtime.cwd}/data/genes_ncbi_10.txt

dir_output: ${hydra:runtime.cwd}/my_out

defaults:
  - specificity_filter: blastn
  - ftp: default
  - melting_temperature: default
  - probe_design: default
