# parameters for melting temperature -> for more information on parameters, see: https://biopython.org/docs/1.75/api/Bio.SeqUtils.MeltingTemp.html#Bio.SeqUtils.MeltingTemp.Tm_NN
Tm_parameters:
    shared:
        check: True
        strict: True
        c_seq: null
        shift: 0
        nn_table: DNA_NN3
        tmm_table: DNA_TMM1
        imm_table: DNA_IMM1
        de_table: DNA_DE1
        dnac1: 50 #[nM]
        dnac2: 0
        selfcomp: False
        dNTPs: 0
        saltcorr: 7
    probe:
        Na: 1.25 #[mM]
        K: 75 #[mM]
        Tris: 20 #[mM]
        Mg: 10 #[mM]
    detection_oligo:
        Na: 39 #[mM]
        K: 0 #[mM]
        Tris: 0 #[mM]
        Mg: 0 #[mM]
Tm_correction_parameters:
    shared:
        DMSO: 0
        DMSOfactor: 0.75
        fmdfactor: 0.65
        fmdmethod: 1
        GC: null
    probe:
        fmd: 20
    detection_oligo:
        fmd: 30
