# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev592+g7e2de6c.d20230316'
__version_tuple__ = version_tuple = (0, 1, 'dev592', 'g7e2de6c.d20230316')
