name: Coverage

on:
  push:
    branches: [main]
    paths-ignore: ['.gitignore', '.pre-commit-config.yaml', '.readthedocs.yaml', 'CONTRIBUTION.md', 'LICENSE', 'MANIFEST.in', 'README.md', 'data/**', 'docs/**', 'tutorials/**']

  workflow_dispatch:

jobs:
  coverage:
    name: Coverage x Ubuntu x Python 3.12

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          auto-update-conda: true
          python-version: "3.12"
          activate-environment: test-env
          channels: conda-forge, bioconda
          channel-priority: strict
          use-mamba: true

      - name: Install system dependencies
        run: |
          conda activate test-env

          mamba install -y \
            "blast>=2.15.0" \
            "bedtools>=2.30" \
            "bowtie>=1.3.1" \
            "bowtie2>=2.5" \
            "samtools>=1.22" \
            "bcftools>=1.22"

      - name: Install Python package
        run: |
          conda activate test-env

          python -m pip install --upgrade pip
          pip install -e .[dev,ai-filters]

      - name: Run coverage
        run: |
          conda activate test-env

          coverage run -m pytest --disable-warnings tests
          coverage xml -i --omit="oligo_designer_toolsuite/pipelines"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
