name: Python Package using Conda

on: 
  push:
    branches: dev

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        auto-activate-base: true
    - name: Install dependencies
      run: |
        conda install -c bioconda blast
        conda install -c bioconda bedtools
        conda install -c bioconda bowtie2
        pip install .
