name: Python Package using Conda

on: 
  push:
    branches: dev

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda update -n base -c defaults conda
        conda install -c bioconda blast
        conda install -c bioconda bedtools
        conda install -c bioconda bowtie
        conda install -c bioconda bowtie2
