name: Conda Environment Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9  # Specify the desired Python version
        auto-update-conda: true
        activate-environment: myenv  # Automatically activate the environment after creation

    - name: Create and Activate Conda Environment
      run: |
        conda create --name myenv python=3.9 -y
        source activate myenv
      shell: bash

    - name: Verify Python Version
      run: python --version
